from typing import Any, Awaitable, Callable, Dict, List, Optional, Union

from astrapy import DataAPIClient, Collection
from astrapy.authentication import TokenProvider
from astrapy.info import CollectionDefinition
from astrapy.constants import DefaultDocumentType, VectorMetric

from midrasai._abc import AsyncVectorDB, VectorDB
from midrasai.types import ColBERT, QueryResult


class AstraDB(VectorDB):
    def __init__(
        self,
        access_token: str | TokenProvider,
        api_endpoint: str,
        **kwargs: Any,
    ):
        self.client = DataAPIClient(access_token)
        self.database = self.client.get_database(api_endpoint)

    def create_index(self, name: str) -> bool:
        """
        Create AstraDB collection under default database

        :param name: Name of the collection, must be used in save_points and search
        :type name: str
        :return: Returns outcome of creating collection
        :rtype: bool
        """
        collection_definition = (
            CollectionDefinition.builder()
            .set_vector_dimension(128)
            .set_vector_metric(VectorMetric.COSINE)
            .build()
        )
        return bool(
            self.database.create_collection(name, definition=collection_definition)
        )

    def create_point(
        self, id: int | str, embedding: ColBERT, data: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        """
        Create documents for a single point (matching your existing interface)

        Args:
            id: Document ID
            embedding: ColBERT embedding (list of vectors)
            data: Metadata for the document

        Returns:
            List of documents to be inserted
        """
        documents = []

        # Create metadata document with embedding_id = -1
        doc_id = str(id)
        metadata_doc = {
            "_id": f"{doc_id}:-1",
            "doc_id": doc_id,
            "embedding_id": -1,
            "metadata": data,
        }
        documents.append(metadata_doc)

        # Create a document for each embedding vector
        for i, vector in enumerate(embedding):
            embedding_doc = {
                "_id": f"{doc_id}:{i}",
                "doc_id": doc_id,
                "embedding_id": i,
                "$vector": vector,
            }
            documents.append(embedding_doc)

        return documents

    def save_points(
        self,
        index: str,
        points: List[List[Dict[str, Any]]],
    ) -> bool:
        """
        Save points to AstraDB

        Args:
            index: Name of the collection
            points: List of point structures generated by create_point

        Returns:
            bool: True if successful
        """
        collection = self.database.get_collection(index)
        documents_to_insert: List[Dict[str, Any]] = []

        for point in points:
            documents_to_insert.extend(point)

        # Insert documents
        success = True
        try:
            result = collection.insert_many(documents_to_insert)
            if not result or result.inserted_ids != len(documents_to_insert):
                success = False
        except Exception as e:
            print(f"Error inserting batch: {e}")
            success = False

        return success

    def delete_index(self, name: str) -> bool:
        try:
            self.database.drop_collection(name)
            return True
        except Exception as e:
            print(f"Error deleting collection {name}: {e}")
            return False

    def search(
        self, index: str, query_embedding: ColBERT, quantity: int, size: int = 10
    ) -> List[QueryResult]:
        """
        Search for documents similar to a ColBERT query embedding

        Args:
            index: Name of the collection
            query_embedding: ColBERT embedding (list of vectors) to search with
            quantity: Maximum number of results to return
            size: The AstraDB query results are indiviual vectors, not full embeddings, so quantity * size is used for actual limit of results returned, default is 10

        Returns:
            List of document metadata with similarity scores
        """
        collection = self.database.get_collection(index)
        # Perform a search with each vector in the ColBERT query embedding
        unique_doc_ids_similarity: Dict[str, int] = {}
        for query_vector in query_embedding:
            # Search for similar vectors
            search_results = collection.find(
                filter={
                    "embedding_id": {"$gte": 0}
                },  # Don't search metadata, which has embedding_id of -1
                projection={"doc_id": True},
                limit=quantity * size,
                include_similarity=True,
                sort={"$vector": query_vector},
            )
            # Process results, keeping track of highest similarity per unique doc_id
            for result in search_results:
                doc_id: str = str(result.get("doc_id"))
                similarity = result.get("$similarity")
                if (
                    doc_id not in unique_doc_ids_similarity
                    or similarity > unique_doc_ids_similarity[doc_id]
                ):
                    unique_doc_ids_similarity[doc_id] = similarity

        # Fetch metadata for each doc_id, create QueryResults
        metadata_docs = collection.find(
            filter={
                "doc_id": {"$in": list(unique_doc_ids_similarity.keys())},
                "embedding_id": -1,
            },
            projection={"doc_id": True, "metadata": True},
        )
        query_results: List[QueryResult] = []
        for metadata_doc in metadata_docs:
            doc_id = str(metadata_doc.get("doc_id"))
            query_results.append(
                QueryResult(
                    id=doc_id,
                    score=unique_doc_ids_similarity[doc_id],
                    data=metadata_doc.get("metadata"),
                )
            )
        # Sort by similarity score
        sorted_results = sorted(
            query_results,
            key=lambda x: x.score,
            reverse=True,
        )[
            :quantity
        ]  # Limit to requested number of results

        return sorted_results
